"""empty message

Revision ID: 009cf2ff3493
Revises: 2ee42df18893
Create Date: 2020-05-26 00:30:12.175208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009cf2ff3493'
down_revision = '2ee42df18893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('friend', sa.Integer(), nullable=False),
    sa.Column('client_group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_group'], ['client_group.client_group_id'], ),
    sa.ForeignKeyConstraint(['friend'], ['friend.friend_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    # ### end Alembic commands ###
