"""empty message

Revision ID: 047890543e77
Revises: 3cc3821a8b17
Create Date: 2020-05-27 00:42:07.099088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047890543e77'
down_revision = '3cc3821a8b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'mail',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'mail',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###
