"""empty message

Revision ID: 14b085345b55
Revises: 2cf253767955
Create Date: 2020-05-27 01:52:24.781643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b085345b55'
down_revision = '2cf253767955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friend_mail_key', 'friend', type_='unique')
    op.drop_column('friend', 'mail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('mail', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.create_unique_constraint('friend_mail_key', 'friend', ['mail'])
    # ### end Alembic commands ###
