"""empty message

Revision ID: 26089dac0e7a
Revises: fa611f06ba40
Create Date: 2020-05-24 20:05:56.216562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26089dac0e7a'
down_revision = 'fa611f06ba40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('present', sa.Column('_from', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'present', 'friend', ['_from'], ['friend_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'present', type_='foreignkey')
    op.drop_column('present', '_from')
    # ### end Alembic commands ###
