"""empty message

Revision ID: 29b09e543f43
Revises: fab2897c2ee3
Create Date: 2020-05-24 18:49:21.574081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b09e543f43'
down_revision = 'fab2897c2ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('test', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
