"""empty message

Revision ID: 2b25a581a459
Revises: 570a2524b3ee
Create Date: 2020-06-02 17:34:01.735019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b25a581a459'
down_revision = '570a2524b3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('password', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'password')
    # ### end Alembic commands ###
