"""empty message

Revision ID: 2cf253767955
Revises: 047890543e77
Create Date: 2020-05-27 01:45:34.994832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf253767955'
down_revision = '047890543e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('present_to_fkey', 'present', type_='foreignkey')
    op.drop_constraint('present__from_fkey', 'present', type_='foreignkey')
    op.create_foreign_key(None, 'present', 'client', ['_from'], ['client_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'present', 'friend', ['to'], ['friend_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'present', type_='foreignkey')
    op.drop_constraint(None, 'present', type_='foreignkey')
    op.create_foreign_key('present__from_fkey', 'present', 'friend', ['_from'], ['friend_id'], ondelete='CASCADE')
    op.create_foreign_key('present_to_fkey', 'present', 'client', ['to'], ['client_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
