"""empty message

Revision ID: 2ee42df18893
Revises: 45d771dd3eb6
Create Date: 2020-05-24 23:14:22.835774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee42df18893'
down_revision = '45d771dd3eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_group',
    sa.Column('client_group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('client_group_id')
    )
    op.create_table('friend_group',
    sa.Column('friend_group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('friend_group_id')
    )
    op.create_table('client_group_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_group_id'], ['client_group.client_group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_group_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('friend_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_group_id'], ['friend_group.friend_group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.friend_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holiday',
    sa.Column('holiday_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.friend_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('holiday_id')
    )
    op.create_table('meeting',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('friend_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['friend_group_id'], ['friend_group.friend_group_id'], ),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    op.drop_column('client', 't')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('t', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.drop_table('meeting')
    op.drop_table('holiday')
    op.drop_table('friend_group_record')
    op.drop_table('client_group_record')
    op.drop_table('friend_group')
    op.drop_table('client_group')
    # ### end Alembic commands ###
