"""empty message

Revision ID: 385acee5aeed
Revises: 349f509f5b9f
Create Date: 2020-06-09 03:31:28.241930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385acee5aeed'
down_revision = '349f509f5b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.friend_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('friend_id'),
    sa.UniqueConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
