"""empty message

Revision ID: 3cc3821a8b17
Revises: 45deb0364a12
Create Date: 2020-05-27 00:41:49.241365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc3821a8b17'
down_revision = '45deb0364a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'mail',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'mail',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###
