"""empty message

Revision ID: 45d771dd3eb6
Revises: 5d259d585a41
Create Date: 2020-05-24 21:55:56.485482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d771dd3eb6'
down_revision = '5d259d585a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('t', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 't')
    # ### end Alembic commands ###
