"""empty message

Revision ID: 570a2524b3ee
Revises: 75f85ae6688e
Create Date: 2020-06-02 17:27:00.853846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570a2524b3ee'
down_revision = '75f85ae6688e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('mail', sa.String(length=40), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('username')
    )
    op.add_column('client', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.drop_constraint('client_mail_key', 'client', type_='unique')
    op.drop_constraint('client_username_key', 'client', type_='unique')
    op.create_unique_constraint(None, 'client', ['profile_id'])
    op.create_foreign_key(None, 'client', 'profile', ['profile_id'], ['profile_id'])
    op.drop_column('client', 'address')
    op.drop_column('client', 'surname')
    op.drop_column('client', 'sex')
    op.drop_column('client', 'birth_date')
    op.drop_column('client', 'mail')
    op.drop_column('client', 'username')
    op.drop_column('client', 'name')
    op.add_column('friend', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.drop_constraint('friend_mail_key', 'friend', type_='unique')
    op.drop_constraint('friend_username_key', 'friend', type_='unique')
    op.create_unique_constraint(None, 'friend', ['profile_id'])
    op.create_foreign_key(None, 'friend', 'profile', ['profile_id'], ['profile_id'])
    op.drop_column('friend', 'address')
    op.drop_column('friend', 'surname')
    op.drop_column('friend', 'sex')
    op.drop_column('friend', 'birth_date')
    op.drop_column('friend', 'mail')
    op.drop_column('friend', 'username')
    op.drop_column('friend', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('friend', sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('friend', sa.Column('mail', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('friend', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('friend', sa.Column('sex', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('friend', sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('friend', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friend', type_='foreignkey')
    op.drop_constraint(None, 'friend', type_='unique')
    op.create_unique_constraint('friend_username_key', 'friend', ['username'])
    op.create_unique_constraint('friend_mail_key', 'friend', ['mail'])
    op.drop_column('friend', 'profile_id')
    op.add_column('client', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('mail', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('sex', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='unique')
    op.create_unique_constraint('client_username_key', 'client', ['username'])
    op.create_unique_constraint('client_mail_key', 'client', ['mail'])
    op.drop_column('client', 'profile_id')
    op.drop_table('profile')
    # ### end Alembic commands ###
