"""empty message

Revision ID: 5d259d585a41
Revises: 
Create Date: 2020-05-24 21:34:13.432266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d259d585a41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('friend',
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('friend_id')
    )
    op.create_table('present',
    sa.Column('present_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('_from', sa.Integer(), nullable=False),
    sa.Column('to', sa.Integer(), nullable=False),
    sa.Column('returned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['_from'], ['friend.friend_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to'], ['client.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('present_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('present')
    op.drop_table('friend')
    op.drop_table('client')
    # ### end Alembic commands ###
