"""empty message

Revision ID: 75f85ae6688e
Revises: 3977eb7bcf66
Create Date: 2020-05-27 02:08:28.906396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f85ae6688e'
down_revision = '3977eb7bcf66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('mail', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'client', ['mail'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_column('client', 'mail')
    # ### end Alembic commands ###
