"""empty message

Revision ID: 7be83d6f1ea2
Revises: 6213fc92fee2
Create Date: 2020-05-27 02:08:03.873691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be83d6f1ea2'
down_revision = '6213fc92fee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'address')
    # ### end Alembic commands ###
