"""empty message

Revision ID: a627baad15a3
Revises: 009cf2ff3493
Create Date: 2020-05-26 23:46:24.096415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a627baad15a3'
down_revision = '009cf2ff3493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('mail', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'client', ['mail'])
    op.add_column('friend', sa.Column('mail', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'friend', ['mail'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friend', type_='unique')
    op.drop_column('friend', 'mail')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_column('client', 'mail')
    # ### end Alembic commands ###
