"""empty message

Revision ID: cf6a127607a4
Revises: dafd89d12076
Create Date: 2020-05-27 01:53:31.902393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6a127607a4'
down_revision = 'dafd89d12076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
