"""empty message

Revision ID: d4b1d8cbd1c1
Revises: 29b09e543f43
Create Date: 2020-05-24 19:00:25.895922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b1d8cbd1c1'
down_revision = '29b09e543f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('test', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend', 'test')
    # ### end Alembic commands ###
