"""empty message

Revision ID: e54f7dcd3c73
Revises: d4b1d8cbd1c1
Create Date: 2020-05-24 19:04:15.239531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54f7dcd3c73'
down_revision = 'd4b1d8cbd1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('test', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
