"""empty message

Revision ID: ed13af4beb21
Revises: 385acee5aeed
Create Date: 2020-06-09 04:46:30.791217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed13af4beb21'
down_revision = '385acee5aeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_profile_id_key', 'user', type_='unique')
    op.drop_constraint('user_profile_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_profile_id_fkey', 'user', 'profile', ['profile_id'], ['profile_id'])
    op.create_unique_constraint('user_profile_id_key', 'user', ['profile_id'])
    # ### end Alembic commands ###
